"""Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms.

By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732
"""


def solve():
    LIMIT = 4000000
    a = 1
    b = 2
    sumValue = 0
    while b < LIMIT:
        sumValue += b
        a2 = a + 2 * b
        b = 2 * a + 3 * b
        a = a2
    return sumValue


if __name__ == '__main__':
    print(solve())
